🚧 GitHub OpenAPI specifications changed
octokit/plugin-rest-endpoint-methods.js pull request #185
Opened 2020-07-31 17:37 UTC by octokitbot

If there are any new endpoints, then the code changes will likely required an update of [`@octokit/types`](https://github.com/octokit/types.ts/pulls). It should have received a pull request as well, merge & release it first, then update the `@octokit/types` version in package.json in this pull request.

Make sure to update the commits so that the merge results in helpful release notes, see [Merging the Pull Request & releasing a new version](https://github.com/octokit/rest.js/blob/master/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

In general

- Avoid breaking changes at all costs
- If there are no typescript or code changes, use a `docs` prefix
- If there are typescript changes but no code changes, use `fix(typescript)` prefix
- If there are code changes, use `fix` if a problem was resolved, `feat` if new endpoints / parameters were added, and `feat(deprecation)` if a method was deprecated.

2020-08-08 00:29 UTC, gr2m requested changes
all the new endpoints introduced in https://github.com/octokit/plugin-rest-endpoint-methods.js/pull/185/commits/007418bab740f0f78ed17a3220baa7728140190b?file-filters%5B%5D=.ts are incorrect, they are all for GitHub Enterprise Cloud only

**Update:** that should be fixed via https://github.com/gr2m/github-openapi-graphql-server/pull/35

2020-08-19 13:53 UTC, alexnder91 requested changes

2020-08-19 13:53 UTC, alexnder91 commented on docs/actions/createSelfHostedRunnerGroupForOrg.md
> +  org,
Номер счета

2020-08-19 13:59 UTC, alexnder91 requested changes

2020-08-19 13:59 UTC, alexnder91 commented on docs/actions/deleteSelfHostedRunnerGroupFromOrg.md
> +
Получить перевод

2020-09-03 19:30 UTC, gr2m submitted a review, later dismissed

2020-09-03 19:47 UTC, merged