edited readme.md
octokit/plugin-rest-endpoint-methods.js pull request #257
Opened 2020-10-25 09:54 UTC by evansusu

2020-10-25 10:04 UTC, evansusu commented
Help guys! I have no idea what is happening!

2020-10-25 17:25 UTC, gr2m requested changes
You nearly got it. Sorry that our code formatter CI is so particular, it helps to keep our code base consistent despite having many contirbutors

2020-10-25 17:25 UTC, gr2m commented on README.md
> +
you will have to remove the empty line. The tests are failing because it checks for file formatting using https://prettier.io/, too

2020-10-31 19:24 UTC, gr2m commented on README.md
> +
Let me fix it for you 👍🏼 

```suggestion
Load `@octokit/plugin-rest-endpoint-methods` and [`@octokit/core`](https://github.com/octokit/core.js) (or core-compatible module) directly from [cdn.skypack.dev](https://cdn.skypack.dev)
```

2020-10-31 19:25 UTC, gr2m commented on README.md
> +
oh you did not give me access to your fork. Can you apply the suggestion above? You should see a big green button below the "Suggested change"

2020-10-31 19:35 UTC, gr2m commented on README.md
> +
nevermind it worked after all :)

2020-10-31 19:46 UTC, gr2m approved these changes
Changes look good now, yay! We will merge your changes shortly, together with other pull requests that address the same issue. We also added the `hacktoberfest-accepted` label so your pull request counts already, in case you are participating.

2020-11-01 17:58 UTC, closed without merging

2020-11-01 17:58 UTC, gr2m commented
Congratulations 🥳 We hope you enjoyed the process of sending the pull requests, and maybe learned a thing or two? If anything was unclear, or if you have any suggestions on how we can improve the suggestions in the issue #123, please let us know! It will help future first time contributors!

If you are looking to make another pull requests, look out for issues with the help wanted label. They are not as straight forward as the first-timers-only issues, but hey, you no longer are a first-timers 🙂 You can find help wanted issues [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Aoctokit+label%3A%22help+wanted%22).
    
You can help us by starring this repository, as well as our primary repository at <https://github.com/octokit/rest.js/> ⭐️ Stars help others to discover our project.
    
If you are interested in Octokit and future opportunities to contribute, you can subscribe to our announcement discussion at <https://github.com/octokit/rest.js/discussions/620>. We will post and update soon and will point out issues you can contribute to.