🚧 GitHub OpenAPI specifications changed
octokit/plugin-rest-endpoint-methods.js pull request #384
Opened 2021-04-30 22:23 UTC by octokitbot

If there are any new endpoints, then the code changes will likely required an update of [`@octokit/types`](https://github.com/octokit/types.ts/pulls). It should have received a pull request as well, merge & release it first. The `@octokit/types` should be updated automatically shortly after in this pull request.

Make sure to update the commits so that the merge results in helpful release notes, see [Merging the Pull Request & releasing a new version](https://github.com/octokit/rest.js/blob/master/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

In general

- Avoid breaking changes at all costs
- If there are no typescript or code changes, use a `docs` prefix
- If there are typescript changes but no code changes, use `fix(typescript)` prefix
- If there are code changes, use `fix` if a problem was resolved, `feat` if new endpoints / parameters were added, and `feat(deprecation)` if a method was deprecated.

2021-04-30 22:37 UTC, gr2m requested changes

2021-04-30 22:37 UTC, gr2m commented on src/generated/endpoints.ts
> +    listAlertInstances: [
This requires a breaking change

2021-04-30 23:07 UTC, gr2m requested changes

2021-04-30 23:07 UTC, gr2m commented on src/generated/endpoints.ts
> +    listAlertsForRepo: ["GET /repos/{owner}/{repo}/code-scanning/alerts"],
This should not have been added.

2021-05-01 17:34 UTC, lastthyme approved these changes

2021-05-21 20:10 UTC, gr2m submitted a review, later dismissed

2021-05-21 20:51 UTC, gr2m approved these changes

2021-05-21 20:51 UTC, merged